### ISSUE TITLE
Add a Code of Conduct

### ISSUE THREAD

**Issue by vidhi-mody** [sauravraghuvanshi/Udacity-Computer-Vision-Nanodegree-Program#19]
A code of conduct defines standards for how to engage in a community. [Read more](https://help.github.com/en/github/building-a-strong-community/adding-a-code-of-conduct-to-your-project)
> Please add the link to the Code of Conduct in the README. [Refer here](https://github.com/twitter/code-of-conduct)

Examples:
- [Twitter](https://github.com/twitter/code-of-conduct/blob/master/code-of-conduct.md)
- [Docker](https://github.com/docker/code-of-conduct/blob/master/code-of-conduct-EN.md)

**Comment by tarunjain1st** [comment]
Can i take this issue

**Comment by vidhi-mody** [comment]
@tarunjain1st sure! You're assigned! 😃

**Comment by vidhi-mody** [comment]
Implemented in #26
