### ISSUE TITLE
Preprocess the images using InceptionV3

### ISSUE THREAD

**Issue by vidhi-mody** [sauravraghuvanshi/Udacity-Computer-Vision-Nanodegree-Program#25]
Resources:
[InceptionV3](https://www.tensorflow.org/api_docs/python/tf/keras/applications/InceptionV3)

> Note: This issue will be implemented in a separate branch. The PRs will not be merged in master.

**Comment by tarushi98** [comment]
I'd like to take this.

**Comment by vidhi-mody** [comment]
@tarushi98 assigned to you! 😃

**Comment by tarushi98** [comment]
Hey @vidhi-mody ! I am done with this. Where do I give the PR?

**Comment by vidhi-mody** [comment]
@sauravraghuvanshi can you create the required branch? I'm not use what naming convention you would want to follow!

**Comment by sauravraghuvanshi** [comment]
@tarushi98 I created a branch, please give your PR in that branch.

**Comment by vidhi-mody** [comment]
@tarushi98 just in case you need to [reference](https://stackoverflow.com/questions/9135913/merge-pull-request-to-a-different-branch-than-default-in-github) for the PR
