### ISSUE TITLE
What is COCO?

### ISSUE THREAD

**Issue by sauravraghuvanshi** [sauravraghuvanshi/Udacity-Computer-Vision-Nanodegree-Program#7]
# Aim
Update readme by writing about COCO and add some links related to it.

# Hint
Use COCO official web page to know about it.

**Comment by tarushi98** [comment]
I'd like to work on this one.

**Comment by tarunjain1st** [comment]
Can i take this issue to go ahead?

**Comment by vidhi-mody** [comment]
@tarushi98 you can go ahead with this! I will add you as the assignee as soon as I have the access rights!

**Comment by vidhi-mody** [comment]
@tarunjain1st this issue is already taken. Would you like to work on something else? There are a lot of similar issues open. Check #11 and #12

**Comment by tarunjain1st** [comment]
@vidhi-mody  yes can i take the #12 issue
